name: "Build and Push to CR"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Img
    environment: tropical-baships
    steps:
      - name: echo path
        run: echo .art/art.yaml
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github container repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/argonautdev/
          username: surya@argonaut.dev
          password: ${{ secrets.ARG_CR_ACCESS_TOKEN }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "ghcr.io/argonautdev//surya@argonaut.dev/baships:latest"
